CREATE TABLE IF NOT EXISTS hits (
    id SERIAL PRIMARY KEY,
    counter INTEGER DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO hits (id, counter) 
SELECT 1, 0 
WHERE NOT EXISTS (SELECT 1 FROM hits WHERE id = 1);
