name: CI Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Show branch name
        run: |
          echo "Running on branch: ${{ github.ref }}"
          echo "Triggered by: ${{ github.event_name }}"}

      # 3. Собрать образ для backend и отправить его на Docker Hub
      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab-backend:latest

      # 4. Собрать образ для frontend и отправить его на Docker Hub
      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab-frontend:latest
